### ISSUE TITLE
Ice3.6 slice2java and omero serveur installation

### ISSUE THREAD

**Issue by remi-fr** [openmicroscopy/openmicroscopy#3953]
Dear all.
I'm trying to install Omero server using homebrew, and the brew install Omero won't terminate successfully saying that "
==> ./build.py -Dice.home=/usr/local/opt/ice build-default
                    *******************************************************
                    Ice is not properly installed. Cannot find slice2java
                    *******************************************************
"
I had macports installed and uninstalled it, I installed xCode which is up to date and its command line tool, Python seems to be installed correctly and the last version of Java as well. I am very near the last idea I can think of so : is there anyone having the same issue ? I understand that Ice 3.6 has just some out so is it possible there is something wrong with both package and is installed automatically by homebrew will installing it with no possibilities to install the version 3.5...
Also when reinstalling Ice is systematically reinstalled wether it already exists on the system or not, as it s very long to install it makes very long to try other ways? is there a way to bypass Ice installation while installing Omero ?

Thanks for your answers.
A good day to all.
Cheers
Rémi

**Comment by sbesson** [comment]
Dear Rémi,

thanks for reporting this issue. Indeed, the mainline Homebrew has switched to ice 3.6 which we is not currently supported by OMERO although adding this support is now planned.
On our Homebrew tap, we have taking a snapshot of the Ice 3.5.1 formula as `zeroc-ice35` (https://github.com/ome/homebrew-alt/pull/82) and updated the OMERO formulas to use this tap instead of the mainline Homebrew `ice` (https://github.com/ome/homebrew-alt/pull/83).

Could you try running `brew update` and try reinstalling OMERO via `brew install` as it should pull the latest version of this formula. Let us know if you encounter any issue.

Best,
Sebastien

**Comment by remi-fr** [comment]
It worked !! 

Thanks a lot.

Cheers !
Rémi

**Comment by remi-fr** [comment]
Well it didn't return any errors but Romero still appears not installed... which is very annoying :)

**Comment by sbesson** [comment]
See https://github.com/openmicroscopy/openmicroscopy/issues/3958
