### ISSUE TITLE
Thumbnail views

### ISSUE THREAD

**Issue by jstitlow** [openmicroscopy/openmicroscopy#4391]
Greetings, by default our OMERO thumbnail viewer shows a single plane of z-series data. I can open the data and look at a max projection and save it, but the thumbnail reverts back to the single plane. Would it be possible to display thumbnails as max projections by default or render the thumbnail as a max projection after it is saved that way?

Many thanks and happy holidays,
Josh

**Comment by jburel** [comment]
First of all, thanks for your interest in OMERO.
In the current implementation, the Thumbnail is generated using the rendering settings associated to the image i.e. a given z and t are set, there is no notion of "projected range" in the current version of the rendering settings.
When you indicate that you save the max projection, do you save it locally as png/tiff/other.?
If you save it as a new image in OMERO, the generated image should only have one z section and the thumbnail will display that plane. This approach has its limitations in the sense that if you project several times with different ranges you will have multiple "projected" OMERO images

We are discussing re-working our rendering strategy so we will keep in mind your suggestion

Thanks again and Happy holidays to you too
Jmarie

**Comment by jstitlow** [comment]
Thank you for replying Jean-Marie,

To answer your question about saving, I am referring to saving within the
OMERO interface. With the image open, I select max project, then click the
edit link to open display settings for the max projection then click save.
The display settings are then updated in the thumbnail but it is just a
single plane, because as you say, there is no setting to show the projected
image.

Thanks for considering this in your revisions. As you know 3D stacks of
data are one of the most common imaging regimes and it having the projected
image in thumbnail view would make it much faster/easier to visualise
datasets.

All the best,
Josh

*Josh Titlow, Ph.D.*
Postdoctoral Research Associate
Department of Biochemistry
University of Oxford, UK

South Parks Road
Oxford OX1 3QU, UK

(p) (44) (0) 1865 613272 (lab)
(w) http://joshtitlow.wordpress.com/

On Fri, Dec 18, 2015 at 10:06 AM, jean-marie burel <notifications@github.com

**Comment by carandraug** [comment]
This issue came up again on a meeting we had today.

Basically, in many images there's no single Z stack that can be used as thumbnail to represent the data well. However, a max intensity projection works nicely. The full viewer already supports "Max Intensity" on its "Viewing Options". An equivalent option on the preview pane would be useful for this case.

On a related note: we have several large datasets where this max intensity projection view would be more useful as preview. Changing this for all individual images would be a pain. An idea for a UI to do this, would be to make use of the "preview" tab (right pane of the web client) which is currently is disabled when multiple images are selected.

**Comment by jstitlow** [comment]
Thanks for keeping us in mind!

We re-visited it again today in our project meeting. As we will be interacting with this large dataset for the foreseeable future a max projected thumbnail option would still be very useful.

J

**Comment by will-moore** [comment]
I have updated the card at https://trello.com/c/JkRcxqVU/118-z-projection-thumbnails

For both the thumbnails and the preview panel, we need to add Projection parameters to the OMERO rendering settings so that they can be saved on an image, copied/pasted between images and "applied to all" images in a Dataset etc.

**Comment by joshmoore** [comment]
Thanks all. Further comments welcome, optimally on the trello card.
