### ISSUE TITLE
Maintain slice definitions in separate repository?

### ISSUE THREAD

**Issue by slnovak** [openmicroscopy/openmicroscopy#4536]
Hi,

What are your thoughts about maintaining OMERO's [Slice files](https://github.com/openmicroscopy/openmicroscopy/tree/develop/components/blitz/resources/omero/api) in a separate repository? I'm interested in developing a Ruby client library that can use those protocols for interacting with OMERO server, but trying to reference those files when they're co-located in the Java source codebase is kind of tricky.

Cheers!

**Comment by joshmoore** [comment]
Hi Stefan,

this is actually something we're slowly but surely [working on](https://trello.com/b/gM86olND/decoupling) but it won't happen in the next few months since it naturally heavily impacts our build system.

One option is to use the files included in the server zip: http://downloads.openmicroscopy.org/omero/5.2.2/artifacts/OMERO.server-5.2.2-ice35-b17.zip

```
downloads.openmicroscopy.org/omero/5.2.2/artifacts $ unzip -l OMERO.server-5.2.2-ice35-b17.zip | grep -E "ice$" | head
     3467  02-28-2016 17:14   OMERO.server-5.2.2-ice35-b17/include/README.ice
    12415  02-28-2016 17:14   OMERO.server-5.2.2-ice35-b17/include/omero/API.ice
     7754  02-28-2016 17:14   OMERO.server-5.2.2-ice35-b17/include/omero/Collections.ice
    10498  02-28-2016 17:14   OMERO.server-5.2.2-ice35-b17/include/omero/Constants.ice
    15708  02-28-2016 17:14   OMERO.server-5.2.2-ice35-b17/include/omero/FS.ice
     1007  02-28-2016 17:14   OMERO.server-5.2.2-ice35-b17/include/omero/Internal.ice
...
```

Again, not ideal, but doable.

Before you embark on this journey, just a warning as the person who wrote the other 3 language mappings, it's fairly costly to add a new language. If you haven't already found it, take a look at https://github.com/openmicroscopy/openmicroscopy/blob/v5.2.2/components/blitz/resources/templates/combined.vm which is used to generate various classes which implement the Ice model interfaces.

I don't know anything about your constraints, but looking at https://github.com/ohsu-computational-biology/search_authorization etc. I should point out that at least one other group has successfully used OMERO from within a JRuby-on-Rails server.

Cheers,
~Josh.

(Closing the issue since actions will be taken via the decoupling board. But feel free to continue commenting here or asking further specific questions on any of the http://openmicroscopy.org/site/community resources.)
