### ISSUE TITLE
[feature request] Python 3 support

### ISSUE THREAD

**Issue by npielawski** [openmicroscopy/openmicroscopy#5980]
Dear developers,

Python 2 is going to end being supported in about 9 months, the 1st of January 2020. Many libraries pledged to stop their support as well, like tensorflow, pandas, numpy, scikit, biopython and many others. A more extensive list is given there: https://python3statement.org/.

Python 3 was released in 2008 and there are many tools to help you convert your code, so you wouldn't to rewrite everything (2to3 for instance). Zeroc-Ice is available for Python 3.6 too. There still would be some work to do, for instance the variable typing that you currently use does not exist any more in Python 3.

Is there any plan on supporting Python 3? Many deep learning applications, newly written libraries and python scripts could benefit from such implementation.

**Comment by joshmoore** [comment]
Hi @npielawski. We're definitely aware of the ticking Python 3 clock. There have been off and on discussions about who, when, and how (e.g. https://trello.com/c/ZE3Cv4uv/111-request-convert-python-api-to-python3). It's not for lack of wanting to support Python 3, but for us it's more than a typical `2to3`-style migration since we need to rewrite our own internal code generation as well. We'll get it done as soon as possible, and you can rest assured there will be an appropriately loud 🎉 from us.

Thanks for your support.
~Josh

**Comment by joshmoore** [comment]
In case you haven't seen it, a version is available for testing: https://forum.image.sc/t/omero-python-3-5-6-milestone-for-upgrade-testing/32120

The final release is in the works!

**Comment by joshmoore** [comment]
See https://www.openmicroscopy.org/2020/01/15/omero-5-6-0.html for the release.
