### ISSUE TITLE
Decoupled Python servers should be used if omero-py from pypi is installed

### ISSUE THREAD

**Issue by manics** [openmicroscopy/openmicroscopy#6103]
OMERO.server Python servers are run using a fixed path:
https://github.com/ome/openmicroscopy/blob/a6977678df03046ea95a9256d33bac85f26f7431/etc/templates/grid/templates.xml#L352
https://github.com/ome/openmicroscopy/blob/a6977678df03046ea95a9256d33bac85f26f7431/etc/templates/grid/default.xml#L19

This means if a decoupled omero-py is installed the starting scripts from that package aren't used. If `OMERO.server/lib/python` is deleted the servers won't be run at all.

**Comment by manics** [comment]
Maybe `runTables.py` should be an entrypoint in omero-py, e.g. `omero-runtables.py`? Or a subcommand, `omero runtables`?

**Comment by joshmoore** [comment]
Another option would be to replace `${OMEROPY_HOME}runProcessor.py` with:

```
<option>-m</option>
<option>runProcessor</option>
```

This would mean that an unpatched phase 2 will require a release of OMERO regardless, likely 5.5.2, in which we should get all such changes if at all possible.

see: https://github.com/ome/openmicroscopy/search?q=OMEROPY_HOME&unscoped_q=OMEROPY_HOME

(Another option would be to suggest _symlinking_ `lib/python` rather than just deleting it.)
